app:
  port: 9090


datasource:
  mysql: 
    url: (192.168.3.162:3306)/ky_used_car?charset=utf8&parseTime=True&loc=UTC
    username: root
    password: 123456


logger:
  console-only: true
  # 日志级别：debug/info/warn/error/dpanic/panic/fatal 参看zapcore level.go文件
  level: debug
  #Filename: 日志文件的位置
  filename: ./log/application.log
  # MaxSize 在进行切割之前，日志文件的最大大小（以MB为单位）
  max-size: 10
  # MaxAges：保留旧文件的最大天数
  max-age: 5
  # MaxBackups：保留旧文件的最大个数
  max-backups:
  # Compress：是否压缩/归档旧文件

file-upload:
  max-size: 5
  file-storage: ./FileStorage #相对路径
  host: http://localhost:9090
  static-fs-path: /files

